env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

language: cpp

services:
  - docker

notifications:
  email: false

before_install:
- docker build -t pidomus docker --build-arg BUILD_TYPE=$BUILD_TYPE
- test -d build-travis || mkdir build-travis; sudo chown -R 1000:1000 build-travis
- ./scripts/dr.sh "cd pi-DoMUS; ./scripts/check_indentation.sh"

script:
- ./scripts/dr.sh "cd pi-DoMUS/build-travis; cmake -GNinja -DENABLE_DOCUMENTATION=OFF -DENABLE_ALL_EXECUTABLES=OFF -DCMAKE_INSTALL_PREFIX=./pi-domus-install -DCMAKE_BUILD_TYPE=$BUILD_TYPE ../; ninja -j2 install"
- ./script/dr.sh "cd pi-DoMUS/build-travis; ctest -j2 -V"
